name: Download OpenJDK 17 Slim

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull and Save Eclipse Temurin 17 Slim
        run: |
          docker pull eclipse-temurin:17-jdk-slim
          docker save eclipse-temurin:17-jdk-slim > openjdk-17-slim.tar

      - name: Upload as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openjdk-17-slim-tar
          path: openjdk-17-slim.tar
